data:
  raw_data_path: 'data/train/train.csv'
  processed_data_path: 'data/processed/'

training:
  test_size: 0.2
  random_state: 42
  model_output_path: 'models/'

model:
  type: 'xgboost'
  parameters:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100

logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
